[variables]
NIXPACKS_RUST_VERSION = "1.85.0"
NIXPACKS_NO_MUSL = "1"

[phases.setup]
nixPkgs = [
  "bash",
  "clang",
  "coreutils",
  "curl",
  "git",
  "iproute2",
  "jq",
  "nodejs_20",
  "openssl",
  "perl",
  "pkg-config",
  "procps",
  "protobuf",
  "gnutar"
]
